### ISSUE TITLE
Should navigability criteria address link shorteners?

### ISSUE THREAD

**Issue by MarjaE2** [w3c/wai-accessibility-principles#26]
I can only find the 2.1 criteria, which don't directly address link shorteners:

https://www.w3.org/WAI/WCAG21/quickref/#navigable

Some of the more aggressive shorteners fail 2.4.4 and 2.4.9. Others don't fail these, but copying shortened or scrambled link text, and pasting into accessibility tools may not work.

**Comment by yatil** [comment]
2.4.4 IMHO addresses this. If you only use the shortened URL as the link text, the exception clause is invoked:

> The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context, **except where the purpose of the link would be ambiguous to users in general.**

If the short URL is used in a link, you have the ability to add a proper link text: `<a href="https://example.com/dkfbvoiwjbq">Product Page</a>`. This is sufficient to meet 2.4.4 and 2.4.9.

If you have further questions around this, we do host an Interest Group discussion list where issues of digital accessibility are discussed.

You can search the mailing list archives, to get a feel for the list, through:
	http://lists.w3.org/Archives/Public/w3c-wai-ig/

You can join the mailing list and post questions by following the instructions about the Discussion List under:
	https://www.w3.org/WAI/about/groups/waiig/#mailinglist
